name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: generate
      run: |
        cd scripts

        node ./get_data.js --user=${{ github.repository_owner }} --gh-token=${{secrets.STATS_PAT}} --file="../stats/data.json" && \
        node ./generate_svgs.js --src="../stats/data.json" --outdir="../stats"
