name: user-statistician

on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: generate
      run: |
        cd scripts
        # get data and generate svgs
        node ./get_data.js --user=${{ github.repository_owner }} --gh-token=${{secrets.GITHUB_TOKEN}} --file="../stats/data.json" && \
        node ./generate_svgs.js --src="../stats/data.json" --outdir="../stats" 
        # cleanup
        rm -f ../stats/data.json
        
    - name: Commit to the repo
      run: |
        git config --global user.name "andypf/andypf"
        git config --global user.email "andypf@users.noreply.github.com"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'Update generated files' || echo
        git push
